In [1]:
import numpy as np

In [2]:
rs = np.random.RandomState(321) # create a random state object
arr = rs.rand(3,4)
print(arr)


[[0.88594794 0.07791236 0.97964616 0.24767146]
 [0.75288472 0.52667564 0.90755375 0.8840703 ]
 [0.08926896 0.5173446  0.34362129 0.21229369]]


### transpose an array

In [3]:
# the following methods return a copy
print(arr.T)
# or 
print('\n', np.transpose(arr))
# or
print('\n',arr.transpose())

print("\n", arr)

[[0.88594794 0.75288472 0.08926896]
 [0.07791236 0.52667564 0.5173446 ]
 [0.97964616 0.90755375 0.34362129]
 [0.24767146 0.8840703  0.21229369]]

 [[0.88594794 0.75288472 0.08926896]
 [0.07791236 0.52667564 0.5173446 ]
 [0.97964616 0.90755375 0.34362129]
 [0.24767146 0.8840703  0.21229369]]

 [[0.88594794 0.75288472 0.08926896]
 [0.07791236 0.52667564 0.5173446 ]
 [0.97964616 0.90755375 0.34362129]
 [0.24767146 0.8840703  0.21229369]]

 [[0.88594794 0.07791236 0.97964616 0.24767146]
 [0.75288472 0.52667564 0.90755375 0.8840703 ]
 [0.08926896 0.5173446  0.34362129 0.21229369]]


### transpose of a high dimensional array with specified order of axes

In [4]:
arr1 = np.arange(16).reshape((2,2,4)) # 3D array
print(arr1)

arr2 =arr1.transpose((1,0,2)) # swap first and second axes
print('\n', arr2)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]

 [[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


### swap axes

In [5]:
arr1 = np.arange(16).reshape((2,2,4)) # 3D array
print(arr1)
print('\n', arr1.swapaxes(1,2)) # swap second and third axes

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]

 [[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


### change the shape of an array

In [6]:
print(arr)
print(arr.shape)
print("\n")
# change the shape of an array and return a copy
arr.reshape((2,6))


[[0.88594794 0.07791236 0.97964616 0.24767146]
 [0.75288472 0.52667564 0.90755375 0.8840703 ]
 [0.08926896 0.5173446  0.34362129 0.21229369]]
(3, 4)




array([[0.88594794, 0.07791236, 0.97964616, 0.24767146, 0.75288472,
        0.52667564],
       [0.90755375, 0.8840703 , 0.08926896, 0.5173446 , 0.34362129,
        0.21229369]])

In [7]:
# change the shape of an array in place
arr.resize((2,6))
print(arr)
print(arr.shape)


[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472 0.52667564]
 [0.90755375 0.8840703  0.08926896 0.5173446  0.34362129 0.21229369]]
(2, 6)


### Flatten an array

| Feature | `array.flatten()` | `array.ravel()` |
| :--- | :--- | :--- |
| **Memory** | **Always** returns a new array (a **Copy**). | Returns a **View** of the original array whenever possible. |
| **Modification** | Changes to the flattened array **do not** affect the original array. | Changes to the raveled array **may** affect the original array (if a view was returned). |
| **Speed** | Generally slower because it involves allocating new memory and copying data. | Generally faster because it avoids copying data, using memory tricks (strides). |
| **Use Case** | When you **must** ensure the original array is never modified. | When performance is critical and you don't mind the potential link to the original data. |

In [8]:
# return a copy
arr.flatten()    

array([0.88594794, 0.07791236, 0.97964616, 0.24767146, 0.75288472,
       0.52667564, 0.90755375, 0.8840703 , 0.08926896, 0.5173446 ,
       0.34362129, 0.21229369])

In [9]:
# return a view
# change any element in the view will change the initial array
arr.ravel()      

array([0.88594794, 0.07791236, 0.97964616, 0.24767146, 0.75288472,
       0.52667564, 0.90755375, 0.8840703 , 0.08926896, 0.5173446 ,
       0.34362129, 0.21229369])

### append elements to an array

In [10]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [11]:
# append a scalar and return a copy
arr1 = np.append(arr, 4)    
print(arr1)

[1 2 3 4]


In [12]:
# append an array and return a copy
arr2 = np.append(arr, [4,5,6])    
print(arr2)

[1 2 3 4 5 6]


### insert elements into an array

In [13]:
# np.insert(array, position, element)

# insert a scalar at a certain position
arr3 = np.insert(arr, 0, 100)    
print(arr3)

[100   1   2   3]


In [14]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 0, [1,2,3])  
print(arr)  
print(arr3)

[1 2 3]
[1 2 3 1 2 3]


### delete elements from an array

In [15]:
# remove the element at position 0
arr4 = np.delete(arr, 0)    
print(arr4)

[2 3]


In [16]:
# remove the element at multiple positions
arr4 = np.delete(arr, [0,2])    
print(arr4)

[2]


### copy an array

In [17]:
arr = np.array([1,2,3])

In [18]:
# the following methods are all deep copy
print(arr)
arr1 = np.copy(arr)
print(arr1)
# or 
arr2 = arr.copy()
print(arr2)
# or 
arr3 = np.array(arr, copy=True)
print(arr3)

[1 2 3]
[1 2 3]
[1 2 3]
[1 2 3]
