In [1]:
import numpy as np

In [2]:
rs = np.random.RandomState(321) # create a random state object
arr = rs.rand(3,5) # create a 3x5 array of random numbers
print(arr)

[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]]


### sort an array along a specified axis

In [3]:
# sort along the column and return a copy
print(np.sort(arr, axis=0))
rsorted_arr = np.sort(arr, axis=0)
sorted_arr = np.sort(arr, axis=0)
print(arr)  # original array remains unsorted

[[0.34362129 0.07791236 0.36067344 0.08926896 0.5173446 ]
 [0.52667564 0.21229369 0.8840703  0.24767146 0.75288472]
 [0.88594794 0.90755375 0.97964616 0.27077517 0.76162502]]
[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]]


In [4]:
# sort along the column in place
arr.sort(axis=0)
print(arr) # now sorted along the column

[[0.34362129 0.07791236 0.36067344 0.08926896 0.5173446 ]
 [0.52667564 0.21229369 0.8840703  0.24767146 0.75288472]
 [0.88594794 0.90755375 0.97964616 0.27077517 0.76162502]]


In [5]:
# sort along the column and return a copy
print(np.sort(arr, axis=1))    

[[0.07791236 0.08926896 0.34362129 0.36067344 0.5173446 ]
 [0.21229369 0.24767146 0.52667564 0.75288472 0.8840703 ]
 [0.27077517 0.76162502 0.88594794 0.90755375 0.97964616]]


In [6]:
# sort along the row in place
arr.sort(axis=1)    
print(arr)

[[0.07791236 0.08926896 0.34362129 0.36067344 0.5173446 ]
 [0.21229369 0.24767146 0.52667564 0.75288472 0.8840703 ]
 [0.27077517 0.76162502 0.88594794 0.90755375 0.97964616]]


### compute the indices that would sort an array along a specified axis

In [7]:
rs = np.random.RandomState(321) # create a random state object
arr = rs.rand(3,5)
print(arr)

[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]]


In [8]:
# along the column - return the indices that would sort the array
print(np.argsort(arr, axis=0))

[[2 0 2 1 1]
 [1 2 1 0 0]
 [0 1 0 2 2]]


In [9]:
# along the row - return the indices that would sort the array
print(np.argsort(arr, axis=1))

[[1 3 4 0 2]
 [3 4 0 2 1]
 [1 3 0 2 4]]


In [10]:
# if axis=None, return the indices of a flattened array
print(np.argsort(arr, axis=None))

[ 1  8 11  3 13 10 12  9  5  4 14  7  0  6  2]


Next [Module](./7.%20Slicing%20&%20Indexing.ipynb)